# Generated by Django 4.2.5 on 2023-09-17 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('social_github', models.ImageField(blank=True, default='Users/user.png', null=True, upload_to='profiles/')),
                ('social_twitter', models.ImageField(blank=True, max_length=2000, null=True, upload_to='')),
                ('social_youtube', models.ImageField(blank=True, max_length=2000, null=True, upload_to='')),
                ('social_linkedin', models.ImageField(blank=True, max_length=2000, null=True, upload_to='')),
                ('social_website', models.ImageField(blank=True, max_length=2000, null=True, upload_to='')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
