# Generated by Django 4.2.5 on 2023-09-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_owner_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
