# Generated by Django 4.2.5 on 2023-09-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
