# Generated by Django 4.2.5 on 2023-09-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_owner_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
