# Generated by Django 4.2.5 on 2023-09-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_profile_image_alter_profile_social_github_and_more'),
        ('project', '0006_remove_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.profile'),
        ),
    ]
