# Generated by Django 4.2.5 on 2023-09-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_owner_profile_user'),
        ('project', '0007_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('project', 'owner')},
        ),
    ]
